services:
    db:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME}
      ports:
        - ${DB_PORT}:3306
      volumes:
        - ./dbdata:/var/lib/mysql/

    adminer:
      image: adminer
      restart: unless-stopped
      environment:
        ADMINER_DEFAULT_DB_DRIVER: mysql
        ADMINER_DEFAULT_DB_HOST: db:3306
        ADMINER_DEFAULT_DB_NAME: ${DB_NAME}
      depends_on:
        - db
      ports:
        - 5050:8080

    backend:
      build:
        context: ./backend
        target: ${NODE_ENV}
      restart: always
      ports:
        - ${BACK_PORT}:3000
      env_file:
        - .env
      depends_on:
        - db
      volumes:
        - ./backend:/usr/src/app
        - /usr/src/app/node_modules/

    frontend:
      build:
        context: ./frontend
        target: ${NODE_ENV}
      restart: always
      ports:
        - ${FRONT_PORT}:3000
      env_file:
        - .env
      depends_on:
        - db
        - backend
      volumes:
        - ./frontend:/usr/src/app
        - /usr/src/app/node_modules/

volumes:
  dbdata: