services:
    db:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - ${DB_PORT}:5432
      volumes:
        - postgres_data:/var/lib/postgresql/data

    postgres_admin:
      image: dpage/pgadmin4
      depends_on:
        - db
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.ru
        PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
      ports:
        - 5050:80

    backend:
      build:
        context: ./backend
        target: ${NODE_ENV}
      restart: always
      ports:
        - ${BACK_PORT}:3000
      env_file:
        - .env
      depends_on:
        - db
      volumes:
        - ./backend:/usr/src/app
        - /usr/src/app/node_modules/

    frontend:
      build:
        context: ./frontend
        target: ${NODE_ENV}
      restart: always
      ports:
        - ${FRONT_PORT}:3000
      env_file:
        - .env
      depends_on:
        - db
      volumes:
        - ./frontend:/usr/src/app
        - /usr/src/app/node_modules/

volumes:
  postgres_data: